server.port=8082
spring.application.name=music
spring.datasource.url=jdbc:mysql://localhost:3306/music?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Jzyww180926.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations: classpath:mapper/*.xml

# ??????
music.upload.audio-path=./uploads/audio/
music.upload.audio-url-prefix=/audio/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# QQ????
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=1445079235@qq.com
spring.mail.password=hphahmvjeltkjbah
spring.mail.default-encoding=UTF-8

# SSL?????465??????
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.qq.com

# ??SMTP??
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.kafka.bootstrap-services=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.kafka.consumer.group-id=test-group
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=1000
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.ack-mode= manual_immediate
product.id=7

# ????
# ??????
logging.level.root=info
# ????????
logging.level.com.example.demo=debug
# ????????
logging.file.path=./logs

# MinIO服务地址，不带桶名
minio.endpoint=http://127.0.0.1:9000
# 账号
minio.access-key=minioadmin
# 密码
minio.secret-key=minioadmin
# 存储桶名称
minio.bucket-name=music
